services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: mydb
    ports:
      - 3306:3306
    volumes:
      - ./volumes:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 88:80
