services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: mydb
    ports:
      - 3306:3306
    volumes:
      - ./volumes:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 88:80

  app:
    image: mynexus:8082/repository/dockerrepo/myimage:1
    restart: always
    ports:
      - 8080:8080
    environment:
        DB_USER: ${DB_USER}
        DB_PWD: ${DB_PWD}
        DB_SERVER: ${DB_SERVER}
        DB_NAME: ${DB_NAME}
